// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/redis/go-redis/v9"
	"go.uber.org/zap"
	"gorm.io/gorm"
	controller2 "interview-guide-go/internal/application/interview/controller"
	repository2 "interview-guide-go/internal/application/interview/repository"
	service2 "interview-guide-go/internal/application/interview/service"
	controller3 "interview-guide-go/internal/application/knowledgebase/controller"
	repository3 "interview-guide-go/internal/application/knowledgebase/repository"
	service3 "interview-guide-go/internal/application/knowledgebase/service"
	controller4 "interview-guide-go/internal/application/ragchat/controller"
	repository4 "interview-guide-go/internal/application/ragchat/repository"
	service4 "interview-guide-go/internal/application/ragchat/service"
	"interview-guide-go/internal/application/resume/controller"
	"interview-guide-go/internal/application/resume/repository"
	"interview-guide-go/internal/application/resume/service"
	"interview-guide-go/internal/config"
	"interview-guide-go/internal/infrastructure/ai"
	adapter4 "interview-guide-go/internal/infrastructure/ai/adapter"
	adapter2 "interview-guide-go/internal/infrastructure/file/adapter"
	"interview-guide-go/internal/infrastructure/postgres/mapper"
	adapter3 "interview-guide-go/internal/infrastructure/redis/adapter"
	"interview-guide-go/internal/infrastructure/storage"
	"interview-guide-go/internal/infrastructure/storage/adapter"
)

// Injectors from wire.go:

// initializeResumeController 生成简历控制器。
// 消费者启动所需的 repository.ResumeWriter 由 deps.go 单独调 mapper.NewResumeMapper 得到（Mapper 只是 *gorm.DB 的薄封装，多实例化无副作用）。
func initializeResumeController(cfg *config.Config, lg *zap.Logger, db *gorm.DB, rdb *redis.Client, storeSvc *storage.StorageService) *controller.ResumeController {
	objectStoragePort := adapter.NewObjectStorageAdapter(storeSvc)
	int64_2 := provideMaxResumeUploadBytes(cfg)
	textExtractor := adapter2.NewTextExtractorAdapter()
	resumeMapper := mapper.NewResumeMapper(db)
	analyzePublisher := adapter3.NewAnalyzePublisher(rdb)
	resumeUploadService := service.NewResumeUploadService(objectStoragePort, int64_2, textExtractor, resumeMapper, analyzePublisher)
	interviewerRolesService := service.NewInterviewerRolesService(lg)
	resumeListService := service.NewResumeListService(lg, resumeMapper)
	resumeDeleteService := service.NewResumeDeleteService(lg, resumeMapper, objectStoragePort)
	resumeDetailService := service.NewResumeDetailService(lg, resumeMapper)
	reanalyzeResumeService := service.NewReanalyzeResumeService(resumeMapper, analyzePublisher, objectStoragePort, textExtractor, lg)
	exportAnalysisPDFService := service.NewExportAnalysisPDFService(resumeDetailService, lg)
	resumeController := &controller.ResumeController{
		UploadService:            resumeUploadService,
		InterviewerRolesService:  interviewerRolesService,
		ResumeListService:        resumeListService,
		ResumeDeleteService:      resumeDeleteService,
		ResumeDetailService:      resumeDetailService,
		ReanalyzeResumeService:   reanalyzeResumeService,
		ExportAnalysisPDFService: exportAnalysisPDFService,
		Logger:                   lg,
	}
	return resumeController
}

// initializeInterviewController 生成面试模块控制器（/api 下 /interview/... 由控制器自行 Route）。
func initializeInterviewController(lg *zap.Logger, db *gorm.DB, rdb *redis.Client, oa *ai.OpenAIService, cfg *config.Config) *controller2.InterviewController {
	interviewMapper := mapper.NewInterviewMapper(db)
	interviewQuestionGenerator := provideInterviewQuestionGenerator(oa, cfg, lg)
	interviewSessionCache := provideInterviewSessionCache(rdb)
	resumeMapper := mapper.NewResumeMapper(db)
	createInterviewService := service2.NewCreateInterviewService(interviewMapper, interviewQuestionGenerator, interviewSessionCache, resumeMapper)
	unfinishedSessionService := service2.NewUnfinishedSessionService(interviewMapper)
	currentQuestionService := service2.NewCurrentQuestionService(interviewMapper)
	evaluateEnqueue := adapter3.NewEvaluateEnqueue(rdb)
	submitAnswerService := service2.NewSubmitAnswerService(interviewMapper, interviewSessionCache, evaluateEnqueue)
	listInterviewSessionsService := service2.NewListInterviewSessionsService(interviewMapper)
	reportService := service2.NewReportService(interviewMapper)
	getInterviewDetailService := service2.NewGetInterviewDetailService(interviewMapper)
	getSessionService := service2.NewGetSessionService(interviewMapper)
	completeSessionService := service2.NewCompleteSessionService(interviewMapper, interviewSessionCache, evaluateEnqueue)
	deleteInterviewService := service2.NewDeleteInterviewService(interviewMapper, interviewSessionCache)
	interviewController := &controller2.InterviewController{
		CreateInterviewService:       createInterviewService,
		UnfinishedSessionService:     unfinishedSessionService,
		CurrentQuestionService:       currentQuestionService,
		SubmitAnswerService:          submitAnswerService,
		ListInterviewSessionsService: listInterviewSessionsService,
		ReportService:                reportService,
		GetInterviewDetailService:    getInterviewDetailService,
		GetSessionService:            getSessionService,
		CompleteSessionService:       completeSessionService,
		DeleteInterviewService:       deleteInterviewService,
		Logger:                       lg,
	}
	return interviewController
}

// initializeKnowledgeBaseController 知识库域（/api/knowledgebase/*），与 initializeResumeController 同形参以复用 StartDeps 注入。
func initializeKnowledgeBaseController(cfg *config.Config, lg *zap.Logger, db *gorm.DB, rdb *redis.Client, storeSvc *storage.StorageService, oa *ai.OpenAIService) *controller3.KnowledgeBaseController {
	objectStoragePort := adapter.NewObjectStorageAdapter(storeSvc)
	knowledgeBaseMapper := mapper.NewKnowledgeBaseMapper(db)
	vectorizeTaskPublisher := adapter3.NewKnowledgeVectorizePublisher(rdb, lg)
	knowledgeTextExtractor := adapter2.NewKnowledgeTextExtractor()
	uploadKnowledgeBaseService := service3.NewUploadKnowledgeBaseService(lg, objectStoragePort, knowledgeBaseMapper, vectorizeTaskPublisher, knowledgeTextExtractor)
	knowledgeBaseListService := service3.NewKnowledgeBaseListService(knowledgeBaseMapper)
	deleteKnowledgeBaseService := service3.NewDeleteKnowledgeBaseService(knowledgeBaseMapper, knowledgeBaseMapper, objectStoragePort)
	downloadKnowledgeBaseService := service3.NewDownloadKnowledgeBaseService(knowledgeBaseMapper, objectStoragePort)
	updateKnowledgeBaseCategoryService := service3.NewUpdateKnowledgeBaseCategoryService(knowledgeBaseMapper, knowledgeBaseMapper)
	revectorizeKnowledgeBaseService := service3.NewRevectorizeKnowledgeBaseService(lg, knowledgeBaseMapper, objectStoragePort, knowledgeBaseMapper, vectorizeTaskPublisher, knowledgeTextExtractor)
	knowledgeTextEmbedder := provideKnowledgeBaseEmbedder(cfg, lg, oa)
	knowledgeBaseQueryChat := provideKnowledgeBaseQueryChat(cfg, oa)
	int2 := provideKBQueryMaxQuestionRunes(cfg)
	knowledgeBaseQueryService := service3.NewKnowledgeBaseQueryService(lg, knowledgeTextEmbedder, knowledgeBaseMapper, knowledgeBaseMapper, knowledgeBaseMapper, knowledgeBaseQueryChat, int2)
	knowledgeBaseController := &controller3.KnowledgeBaseController{
		UploadService:         uploadKnowledgeBaseService,
		ListService:           knowledgeBaseListService,
		DeleteService:         deleteKnowledgeBaseService,
		DownloadService:       downloadKnowledgeBaseService,
		UpdateCategoryService: updateKnowledgeBaseCategoryService,
		RevectorizeService:    revectorizeKnowledgeBaseService,
		QueryService:          knowledgeBaseQueryService,
	}
	return knowledgeBaseController
}

// initializeRagChatController RAG 对话域（/api/rag-chat/*），依赖 Postgres + OpenAI（KB 问答链）。
func initializeRagChatController(cfg *config.Config, lg *zap.Logger, db *gorm.DB, oa *ai.OpenAIService) *controller4.RagChatController {
	ragChatMapper := mapper.NewRagChatMapper(db)
	ragChatSessionService := service4.NewRagChatSessionService(ragChatMapper)
	knowledgeTextEmbedder := provideKnowledgeBaseEmbedder(cfg, lg, oa)
	knowledgeBaseMapper := mapper.NewKnowledgeBaseMapper(db)
	knowledgeBaseQueryChat := provideKnowledgeBaseQueryChat(cfg, oa)
	int2 := provideKBQueryMaxQuestionRunes(cfg)
	knowledgeBaseQueryService := service3.NewKnowledgeBaseQueryService(lg, knowledgeTextEmbedder, knowledgeBaseMapper, knowledgeBaseMapper, knowledgeBaseMapper, knowledgeBaseQueryChat, int2)
	ragChatStreamService := service4.NewRagChatStreamService(lg, ragChatMapper, knowledgeBaseQueryService)
	ragChatController := &controller4.RagChatController{
		SessionService: ragChatSessionService,
		StreamService:  ragChatStreamService,
	}
	return ragChatController
}

// wire.go:

// 一捆「能生产东西的函数」，Wire 会在这捆里解依赖图。
var resumeModuleSet = wire.NewSet(
	provideMaxResumeUploadBytes, mapper.NewResumeMapper, wire.Bind(new(repository.ResumeWriter), new(*mapper.ResumeMapper)), adapter.NewObjectStorageAdapter, adapter3.NewAnalyzePublisher, adapter2.NewTextExtractorAdapter, service.NewResumeUploadService, service.NewInterviewerRolesService, service.NewResumeListService, service.NewResumeDeleteService, service.NewResumeDetailService, service.NewReanalyzeResumeService, service.NewExportAnalysisPDFService, wire.Struct(new(controller.ResumeController), "*"),
)

// 面试模块：会话写库、简历人设（*ResumeMapper 实现 InterviewerRoleReader）、缓存、出题、CreateInterview 用例、控制器。
var interviewModuleSet = wire.NewSet(mapper.NewResumeMapper, wire.Bind(new(repository2.InterviewerRoleReader), new(*mapper.ResumeMapper)), wire.Bind(new(repository2.ResumeTextSource), new(*mapper.ResumeMapper)), mapper.NewInterviewMapper, wire.Bind(new(repository2.InterviewSessionWriter), new(*mapper.InterviewMapper)), adapter3.NewEvaluateEnqueue, wire.Bind(new(repository2.InterviewEvaluateEnqueuer), new(*adapter3.EvaluateEnqueue)), provideInterviewSessionCache,
	provideInterviewQuestionGenerator, service2.NewCreateInterviewService, service2.NewUnfinishedSessionService, service2.NewCurrentQuestionService, service2.NewSubmitAnswerService, service2.NewListInterviewSessionsService, service2.NewReportService, service2.NewGetInterviewDetailService, service2.NewGetSessionService, service2.NewCompleteSessionService, service2.NewDeleteInterviewService, wire.Struct(new(controller2.InterviewController), "*"),
)

// 知识库：上传、列表、向量检索问答（query/query/stream）、下载、重向量化等。
var knowledgeModuleSet = wire.NewSet(mapper.NewKnowledgeBaseMapper, wire.Bind(new(repository3.KnowledgeBaseWriter), new(*mapper.KnowledgeBaseMapper)), wire.Bind(new(repository3.KnowledgeBaseReader), new(*mapper.KnowledgeBaseMapper)), wire.Bind(new(repository3.KnowledgeVectorSearcher), new(*mapper.KnowledgeBaseMapper)), adapter.NewObjectStorageAdapter, adapter2.NewKnowledgeTextExtractor, adapter3.NewKnowledgeVectorizePublisher, provideKnowledgeBaseEmbedder,
	provideKnowledgeBaseQueryChat,
	provideKBQueryMaxQuestionRunes, service3.NewUploadKnowledgeBaseService, service3.NewKnowledgeBaseListService, service3.NewDeleteKnowledgeBaseService, service3.NewDownloadKnowledgeBaseService, service3.NewUpdateKnowledgeBaseCategoryService, service3.NewRevectorizeKnowledgeBaseService, service3.NewKnowledgeBaseQueryService, wire.Struct(new(controller3.KnowledgeBaseController), "*"),
)

// RAG 对话：会话 CRUD + messages/stream（复用 KnowledgeBaseQueryService RAG 链）。
var ragModuleSet = wire.NewSet(mapper.NewKnowledgeBaseMapper, wire.Bind(new(repository3.KnowledgeBaseWriter), new(*mapper.KnowledgeBaseMapper)), wire.Bind(new(repository3.KnowledgeBaseReader), new(*mapper.KnowledgeBaseMapper)), wire.Bind(new(repository3.KnowledgeVectorSearcher), new(*mapper.KnowledgeBaseMapper)), provideKnowledgeBaseEmbedder,
	provideKnowledgeBaseQueryChat,
	provideKBQueryMaxQuestionRunes, service3.NewKnowledgeBaseQueryService, mapper.NewRagChatMapper, wire.Bind(new(repository4.RagChatRepository), new(*mapper.RagChatMapper)), service4.NewRagChatSessionService, service4.NewRagChatStreamService, wire.Struct(new(controller4.RagChatController), "*"),
)

// provideMaxResumeUploadBytes 抽取 cfg 字段给 ResumeUploadService 用，避免 wire 直接把 cfg.Xxx 当 int64 provider。
func provideMaxResumeUploadBytes(cfg *config.Config) int64 {
	return cfg.MaxResumeUploadBytes
}

// provideInterviewSessionCache 将 *redisadapter.SessionCache 以接口形式注入，避免与 NewSessionCache 的重复 interface 绑定。
func provideInterviewSessionCache(rdb *redis.Client) repository2.InterviewSessionCache {
	return adapter3.NewSessionCache(rdb)
}

// provideInterviewQuestionGenerator 依赖可用的 OpenAI 客户端；不满足则 panic（禁止 Stub 兜底）。
func provideInterviewQuestionGenerator(oa *ai.OpenAIService, cfg *config.Config, lg *zap.Logger) repository2.InterviewQuestionGenerator {
	if oa == nil {
		panic("interview-guide-go: OpenAIService required for InterviewQuestionGenerator")
	}
	return adapter4.NewOpenAIInterviewQuestionGenerator(oa, cfg, lg)
}

// provideKnowledgeBaseEmbedder 与向量化消费者同源：KB_EMBEDDING_* 网关 + OpenAIKnowledgeEmbedder。
func provideKnowledgeBaseEmbedder(cfg *config.Config, lg *zap.Logger, oa *ai.OpenAIService) repository3.KnowledgeTextEmbedder {
	c, err := ai.EmbeddingHTTPClient(cfg, oa)
	if err != nil {
		panic("interview-guide-go: EmbeddingHTTPClient: " + err.Error())
	}
	return adapter4.NewOpenAIKnowledgeEmbedder(c, cfg.Openai, lg)
}

// provideKnowledgeBaseQueryChat 主对话网关 Chat Completions（OPENAI_*），供 query / query/stream 生成答案。
func provideKnowledgeBaseQueryChat(cfg *config.Config, oa *ai.OpenAIService) repository3.KnowledgeBaseQueryChat {
	if cfg == nil || oa == nil {
		panic("interview-guide-go: KnowledgeBaseQueryChat prerequisites")
	}
	o := cfg.Openai
	return adapter4.NewKnowledgeBaseQueryChatAdapter(oa, o.AIModel, o.ResumeAIMaxCompletionTokens, o.ResumeAITemperature)
}

// provideKBQueryMaxQuestionRunes 抽 cfg，供注入 KnowledgeBaseQueryService（问题过长按 rune 截断）。
func provideKBQueryMaxQuestionRunes(cfg *config.Config) int {
	if cfg == nil {
		return 0
	}
	return cfg.Openai.ResumeAIMaxRunes
}
