// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/redis/go-redis/v9"
	"go.uber.org/zap"
	"gorm.io/gorm"
	controller2 "interview-guide-go/internal/application/interview/controller"
	repository2 "interview-guide-go/internal/application/interview/repository"
	service2 "interview-guide-go/internal/application/interview/service"
	controller3 "interview-guide-go/internal/application/knowledgebase/controller"
	repository3 "interview-guide-go/internal/application/knowledgebase/repository"
	service3 "interview-guide-go/internal/application/knowledgebase/service"
	"interview-guide-go/internal/application/resume/controller"
	"interview-guide-go/internal/application/resume/repository"
	"interview-guide-go/internal/application/resume/service"
	"interview-guide-go/internal/config"
	"interview-guide-go/internal/infrastructure/ai"
	adapter4 "interview-guide-go/internal/infrastructure/ai/adapter"
	adapter2 "interview-guide-go/internal/infrastructure/file/adapter"
	"interview-guide-go/internal/infrastructure/postgres/mapper"
	adapter3 "interview-guide-go/internal/infrastructure/redis/adapter"
	"interview-guide-go/internal/infrastructure/storage"
	"interview-guide-go/internal/infrastructure/storage/adapter"
)

// Injectors from wire.go:

// initializeResumeController 生成简历控制器。
// 消费者启动所需的 repository.ResumeWriter 由 deps.go 单独调 mapper.NewResumeMapper 得到（Mapper 只是 *gorm.DB 的薄封装，多实例化无副作用）。
func initializeResumeController(cfg *config.Config, lg *zap.Logger, db *gorm.DB, rdb *redis.Client, storeSvc *storage.StorageService) *controller.ResumeController {
	objectStoragePort := adapter.NewObjectStorageAdapter(storeSvc)
	int64_2 := provideMaxResumeUploadBytes(cfg)
	textExtractor := adapter2.NewTextExtractorAdapter()
	resumeMapper := mapper.NewResumeMapper(db)
	analyzePublisher := adapter3.NewAnalyzePublisher(rdb)
	resumeUploadService := service.NewResumeUploadService(objectStoragePort, int64_2, textExtractor, resumeMapper, analyzePublisher)
	interviewerRolesService := service.NewInterviewerRolesService(lg)
	resumeListService := service.NewResumeListService(lg, resumeMapper)
	resumeDeleteService := service.NewResumeDeleteService(lg, resumeMapper, objectStoragePort)
	resumeDetailService := service.NewResumeDetailService(lg, resumeMapper)
	reanalyzeResumeService := service.NewReanalyzeResumeService(resumeMapper, analyzePublisher, objectStoragePort, textExtractor, lg)
	exportAnalysisPDFService := service.NewExportAnalysisPDFService(resumeDetailService, lg)
	resumeController := &controller.ResumeController{
		UploadService:            resumeUploadService,
		InterviewerRolesService:  interviewerRolesService,
		ResumeListService:        resumeListService,
		ResumeDeleteService:      resumeDeleteService,
		ResumeDetailService:      resumeDetailService,
		ReanalyzeResumeService:   reanalyzeResumeService,
		ExportAnalysisPDFService: exportAnalysisPDFService,
		Logger:                   lg,
	}
	return resumeController
}

// initializeInterviewController 生成面试模块控制器（/api 下 /interview/... 由控制器自行 Route）。
func initializeInterviewController(lg *zap.Logger, db *gorm.DB, rdb *redis.Client, oa *ai.OpenAIService, cfg *config.Config) *controller2.InterviewController {
	interviewMapper := mapper.NewInterviewMapper(db)
	interviewQuestionGenerator := provideInterviewQuestionGenerator(oa, cfg, lg)
	interviewSessionCache := provideInterviewSessionCache(rdb)
	resumeMapper := mapper.NewResumeMapper(db)
	createInterviewService := service2.NewCreateInterviewService(interviewMapper, interviewQuestionGenerator, interviewSessionCache, resumeMapper)
	unfinishedSessionService := service2.NewUnfinishedSessionService(interviewMapper)
	currentQuestionService := service2.NewCurrentQuestionService(interviewMapper)
	evaluateEnqueue := adapter3.NewEvaluateEnqueue(rdb)
	submitAnswerService := service2.NewSubmitAnswerService(interviewMapper, interviewSessionCache, evaluateEnqueue)
	listInterviewSessionsService := service2.NewListInterviewSessionsService(interviewMapper)
	reportService := service2.NewReportService(interviewMapper)
	getInterviewDetailService := service2.NewGetInterviewDetailService(interviewMapper)
	getSessionService := service2.NewGetSessionService(interviewMapper)
	completeSessionService := service2.NewCompleteSessionService(interviewMapper, interviewSessionCache, evaluateEnqueue)
	deleteInterviewService := service2.NewDeleteInterviewService(interviewMapper, interviewSessionCache)
	interviewController := &controller2.InterviewController{
		CreateInterviewService:       createInterviewService,
		UnfinishedSessionService:     unfinishedSessionService,
		CurrentQuestionService:       currentQuestionService,
		SubmitAnswerService:          submitAnswerService,
		ListInterviewSessionsService: listInterviewSessionsService,
		ReportService:                reportService,
		GetInterviewDetailService:    getInterviewDetailService,
		GetSessionService:            getSessionService,
		CompleteSessionService:       completeSessionService,
		DeleteInterviewService:       deleteInterviewService,
		Logger:                       lg,
	}
	return interviewController
}

// initializeKnowledgeBaseController 知识库域（/api/knowledgebase/*），与 initializeResumeController 同形参以复用 StartDeps 注入。
func initializeKnowledgeBaseController(cfg *config.Config, lg *zap.Logger, db *gorm.DB, rdb *redis.Client, storeSvc *storage.StorageService) *controller3.KnowledgeBaseController {
	v := adapter.NewObjectStorageAdapter(storeSvc)
	knowledgeBaseMapper := mapper.NewKnowledgeBaseMapper(db)
	vectorizeTaskPublisher := adapter3.NewKnowledgeVectorizePublisher(rdb)
	knowledgeTextExtractor := adapter2.NewKnowledgeTextExtractor()
	uploadKnowledgeBaseService := service3.NewUploadKnowledgeBaseService(v, knowledgeBaseMapper, vectorizeTaskPublisher, knowledgeTextExtractor)
	knowledgeBaseController := &controller3.KnowledgeBaseController{
		UploadService: uploadKnowledgeBaseService,
	}
	return knowledgeBaseController
}

// wire.go:

// 一捆「能生产东西的函数」，Wire 会在这捆里解依赖图。
var resumeModuleSet = wire.NewSet(
	provideMaxResumeUploadBytes, mapper.NewResumeMapper, wire.Bind(new(repository.ResumeWriter), new(*mapper.ResumeMapper)), adapter.NewObjectStorageAdapter, adapter3.NewAnalyzePublisher, adapter2.NewTextExtractorAdapter, service.NewResumeUploadService, service.NewInterviewerRolesService, service.NewResumeListService, service.NewResumeDeleteService, service.NewResumeDetailService, service.NewReanalyzeResumeService, service.NewExportAnalysisPDFService, wire.Struct(new(controller.ResumeController), "*"),
)

// 面试模块：会话写库、简历人设（*ResumeMapper 实现 InterviewerRoleReader）、缓存、出题、CreateInterview 用例、控制器。
var interviewModuleSet = wire.NewSet(mapper.NewResumeMapper, wire.Bind(new(repository2.InterviewerRoleReader), new(*mapper.ResumeMapper)), wire.Bind(new(repository2.ResumeTextSource), new(*mapper.ResumeMapper)), mapper.NewInterviewMapper, wire.Bind(new(repository2.InterviewSessionWriter), new(*mapper.InterviewMapper)), adapter3.NewEvaluateEnqueue, wire.Bind(new(repository2.InterviewEvaluateEnqueuer), new(*adapter3.EvaluateEnqueue)), provideInterviewSessionCache,
	provideInterviewQuestionGenerator, service2.NewCreateInterviewService, service2.NewUnfinishedSessionService, service2.NewCurrentQuestionService, service2.NewSubmitAnswerService, service2.NewListInterviewSessionsService, service2.NewReportService, service2.NewGetInterviewDetailService, service2.NewGetSessionService, service2.NewCompleteSessionService, service2.NewDeleteInterviewService, wire.Struct(new(controller2.InterviewController), "*"),
)

// 知识库：上传（存储 + 文本抽取 + 落库 + 向量化入队）与其它端点仍多为占位。
var knowledgeModuleSet = wire.NewSet(mapper.NewKnowledgeBaseMapper, wire.Bind(new(repository3.KnowledgeBaseWriter), new(*mapper.KnowledgeBaseMapper)), adapter.NewObjectStorageAdapter, adapter2.NewKnowledgeTextExtractor, adapter3.NewKnowledgeVectorizePublisher, service3.NewUploadKnowledgeBaseService, wire.Struct(new(controller3.KnowledgeBaseController), "*"))

// provideMaxResumeUploadBytes 抽取 cfg 字段给 ResumeUploadService 用，避免 wire 直接把 cfg.Xxx 当 int64 provider。
func provideMaxResumeUploadBytes(cfg *config.Config) int64 {
	return cfg.MaxResumeUploadBytes
}

// provideInterviewSessionCache 将 *redisadapter.SessionCache 以接口形式注入，避免与 NewSessionCache 的重复 interface 绑定。
func provideInterviewSessionCache(rdb *redis.Client) repository2.InterviewSessionCache {
	return adapter3.NewSessionCache(rdb)
}

// provideInterviewQuestionGenerator OpenAI 客户端未就绪时退回 Stub，与 deps 中 oa 启动失败时一致。
func provideInterviewQuestionGenerator(oa *ai.OpenAIService, cfg *config.Config, lg *zap.Logger) repository2.InterviewQuestionGenerator {
	if oa == nil {
		return ai.NewStubInterviewQuestionGenerator()
	}
	return adapter4.NewOpenAIInterviewQuestionGenerator(oa, cfg, lg)
}
